// Dispara el actor streamers/youtube-scraper para una búsqueda (palabra clave) y devuelve los videos.

import { config } from './config.js';
import { runActorItems } from './apifyRun.js';

// Corre el actor para una sola búsqueda y espera a que termine.
// onlyNewerThan: fecha ISO o relativo ("7 days"); limita a videos publicados desde entonces.
export async function scrapeSearchVideos({ query, maxResults, maxShorts, onlyNewerThan }) {
  const input = {
    searchQueries: [query],
    maxResults,
    maxResultsShorts: maxShorts || 0,
    maxResultStreams: 0,
    sortingOrder: 'date',
    downloadSubtitles: config.youtubeDownloadSubtitles,
    subtitlesFormat: 'plaintext',
    subtitlesLanguage: 'any',
    preferAutoGeneratedSubtitles: true,
  };
  if (onlyNewerThan) input.oldestPostDate = onlyNewerThan;

  const items = await runActorItems(config.youtubeActorId, input);
  // Descarta items de error y los que no traen id de video.
  return items.filter((it) => it && it.id && !it.error);
}

// Corre el actor para un canal (URL) y devuelve sus videos más nuevos.
export async function scrapeChannelVideos({ channelUrl, maxResults, maxShorts, onlyNewerThan }) {
  const input = {
    startUrls: [{ url: channelUrl }],
    maxResults, // para canales actúa como límite de videos regulares
    maxResultsShorts: maxShorts || 0,
    maxResultStreams: 0,
    sortVideosBy: 'NEWEST',
    downloadSubtitles: config.youtubeDownloadSubtitles,
    subtitlesFormat: 'plaintext',
    subtitlesLanguage: 'any',
    preferAutoGeneratedSubtitles: true,
  };
  if (onlyNewerThan) input.oldestPostDate = onlyNewerThan;

  const items = await runActorItems(config.youtubeActorId, input);
  return items.filter((it) => it && it.id && !it.error);
}

// Trae los videos de una lista de URLs (para backfill de subtítulos de videos ya guardados).
export async function scrapeVideosByUrls(urls) {
  const input = {
    startUrls: urls.map((u) => ({ url: u })),
    maxResults: urls.length,
    maxResultsShorts: 0,
    maxResultStreams: 0,
    downloadSubtitles: true,
    subtitlesFormat: 'plaintext',
    subtitlesLanguage: 'any',
    preferAutoGeneratedSubtitles: true,
  };
  const items = await runActorItems(config.youtubeActorId, input);
  return items.filter((it) => it && it.id && !it.error);
}
