// Dispara el actor streamers/youtube-scraper en modo batched: varias búsquedas o varios canales
// en UNA sola corrida (el actor aplica maxResults por fuente; oldestPostDate es global).

import { config } from './config.js';
import { runActorItems } from './apifyRun.js';

const subtitleOpts = {
  downloadSubtitles: config.youtubeDownloadSubtitles,
  subtitlesFormat: 'plaintext',
  subtitlesLanguage: 'any',
  preferAutoGeneratedSubtitles: true,
};

// Varias búsquedas (palabras clave) en una sola corrida.
export async function scrapeSearches({ queries, maxResults, maxShorts, onlyNewerThan }) {
  const input = {
    searchQueries: queries,
    maxResults,
    maxResultsShorts: maxShorts || 0,
    maxResultStreams: 0,
    sortingOrder: 'date',
    ...subtitleOpts,
  };
  if (onlyNewerThan) input.oldestPostDate = onlyNewerThan;
  const items = await runActorItems(config.youtubeActorId, input);
  return items.filter((it) => it && it.id && !it.error);
}

// Varios canales (URLs) en una sola corrida.
export async function scrapeChannels({ urls, maxResults, maxShorts, onlyNewerThan }) {
  const input = {
    startUrls: urls.map((u) => ({ url: u })),
    maxResults, // por canal
    maxResultsShorts: maxShorts || 0,
    maxResultStreams: 0,
    sortVideosBy: 'NEWEST',
    ...subtitleOpts,
  };
  if (onlyNewerThan) input.oldestPostDate = onlyNewerThan;
  const items = await runActorItems(config.youtubeActorId, input);
  return items.filter((it) => it && it.id && !it.error);
}

// Trae los videos de una lista de URLs (para backfill de subtítulos de videos ya guardados).
export async function scrapeVideosByUrls(urls) {
  const input = {
    startUrls: urls.map((u) => ({ url: u })),
    maxResults: urls.length,
    maxResultsShorts: 0,
    maxResultStreams: 0,
    downloadSubtitles: true,
    subtitlesFormat: 'plaintext',
    subtitlesLanguage: 'any',
    preferAutoGeneratedSubtitles: true,
  };
  const items = await runActorItems(config.youtubeActorId, input);
  return items.filter((it) => it && it.id && !it.error);
}
